#YAML Manifest to create a StorageSystem resource within the openshift-storage namespace

apiVersion: odf.openshift.io/v1alpha1
kind: StorageSystem
metadata:
 name: ocs-storagecluster-storagesystem
 namespace: openshift-storage
spec:
 kind: storagecluster.ocs.openshift.io/v1
 name: ocs-storagecluster
 namespace: openshift-storage
