---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ cp4na_ns }}

---
apiVersion: v1
stringData:
  LDAP_ADMIN_PASSWORD: {{ ldap_admin_password }}
  LDAP_BASE_DN: {{ ldap_base_dn }}
  LDAP_BIND_DN: {{ ldap_bind_dn }}
  LDAP_PASSWORD_ATTR: {{ ldap_password_attr }}
  LDAP_URL: {{ ldap_url }}
  LDAP_USER_SEARCH_BASE: {{ ldap_user_search_base }}
  LDAP_USER_SEARCH_FILTER: {{ ldap_user_search_filter }}
kind: Secret
metadata:
  creationTimestamp: null
  name: ldap
  namespace: {{ cp4na_ns }}

---
apiVersion: v1
data:
  .dockerconfigjson: {{ ibm_key_credjson }}
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: ibm-entitlement-key
  namespace: {{ cp4na_ns }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
  app: ibm-alm-prod
  name: alm-serviceaccount
  namespace: {{ cp4na_ns }}
imagePullSecrets:
- name: ibm-entitlement-key

---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: IBM Operator Catalog
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/ibm-operator-catalog
  updateStrategy:
    registryPoll:
      interval: 45m

---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: opencloud-operators
  namespace: openshift-marketplace
spec:
  displayName: IBMCS Operators
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/ibm-common-service-catalog:latest
  updateStrategy:
    registryPoll:
      interval: 45m

---
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: ibm-tnc-orchestration-catalog-group
  namespace: {{ cp4na_ns }}
spec:
  targetNamespaces:
    - {{ cp4na_ns }}

---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
    name: ibm-tnc-orchestration-subscription
    namespace: {{ cp4na_ns }}
spec:
    channel: {{ channel_version }}
    installPlanApproval: Automatic
    name: ibm-tnc-orchestration-operator
    source: ibm-operator-catalog
    sourceNamespace: openshift-marketplace
