---
- name: create the {{ dhcp_conf_dir }} directory if it does not exist
  ansible.builtin.file:
    path: "{{ dhcp_conf_dir }}"
    state: directory
    mode: '0755'

- name: create the '{{ dhcp_conf_file }}'
  template:
    src: dnsmasq.conf.j2
    dest: "{{ dhcp_conf_dir}}/{{ dhcp_conf_file }}"
