---
- name: cp4na operator install playbook
  hosts: localhost
  roles:
    - role: cp4na_subscription_edit
      vars:
        ansible_work_dir: /ansible
        cp4na_ns: ibmcp4na
        file_dest_dir: /home/cp4na_yaml_files
        ip_approval_method: Manual
        role_name: cp4na_subscription_edit
        
