---
- name: Download and apply kubernetes yaml manifests for the creation of StorageSystem resource
  hosts: localhost

  tasks:
  - name: Download creation of StorageSystem resource yaml manifest file from github repo
    ansible.builtin.get_url:
      url: https://raw.githubusercontent.com/redhat-eets/cp4na/main/odf_operator/05_create_storage_system.yaml
      dest: /home/odf_yaml_files/05_create_storage_system.yaml
      mode: '0664'


  - name: Apply creation of StorageSystem resource yaml manifest file
    kubernetes.core.k8s:
      state: present
      src: /home/odf_yaml_files/05_create_storage_system.yaml
~                                                               
